CREATE USER $FINERACT_DB_USER WITH PASSWORD '$FINERACT_DB_PASS';
CREATE DATABASE $FINERACT_TENANTS_DB_NAME;
CREATE DATABASE $FINERACT_TENANT_DEFAULT_DB_NAME;

GRANT ALL PRIVILEGES ON DATABASE $FINERACT_TENANTS_DB_NAME TO $FINERACT_DB_USER;
GRANT ALL PRIVILEGES ON DATABASE $FINERACT_TENANT_DEFAULT_DB_NAME TO $FINERACT_DB_USER;

-- LOG IN TO '${FINERACT_TENANTS_DB_NAME}' database and run this
GRANT ALL ON SCHEMA public TO $FINERACT_DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $FINERACT_DB_USER;

-- LOG IN TO '${FINERACT_TENANT_DEFAULT_DB_NAME}' database and run this
GRANT ALL ON SCHEMA public TO $FINERACT_DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $FINERACT_DB_USER;





